### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by orkuncaylar** [carchaze-org/react-native-voice-message-player#1]
You should share more examples. I've been trying to get it to work for about 3-4 hours.

**Comment by Gabotron-ES** [comment]
> You should share more examples. I've been trying to get it to work for about 3-4 hours.

Did you get it to work? Could you please post your example?

**Comment by hamxahussain** [comment]
This package is currently being development. Currently, it have slight issues after the fix I will publish it again, for now, its status will change to under-maintenance.

**Comment by ghost** [comment]
Anyone can please share an example.
