### ISSUE TITLE
For basic developer

### ISSUE THREAD

**Issue by refrescodev** [carchaze-org/react-native-voice-message-player#2]
I am a newbie react native developer.
So I cant use your npm module well.
I would like you post more example about your module

**Comment by Gabotron-ES** [comment]
> I am a newbie react native developer. So I cant use your npm module well. I would like you post more example about your module

Did you get it to work? Could you please post your example?

**Comment by refrescodev** [comment]
> > I am a newbie react native developer. So I cant use your npm module well. I would like you post more example about your module
> 
> Did you get it to work? Could you please post your example?
I did not implement react-native-voice-message module perfectly. So I need help.

**Comment by hamxahussain** [comment]
This package is currently being development. Currently, it has slight issues after the fix I will publish it again, for now, its status will change to under-maintenance.
