### ISSUE TITLE
 it also have issue which says : createAnimatedMode: Animated node [3] already exists

### ISSUE THREAD

**Issue by ahmedIcots** [carchaze-org/react-native-voice-message-player#3]
it also have issue which says : createAnimatedMode: Animated node [3] already exists

**Comment by hamxahussain** [comment]
This package is currently being development. Currently, it have slight issues after the fix I will publish it again, for now, its status will change to under-maintenance.

**Comment by ahmedIcots** [comment]
when did you solve this issue? also kindly add Fft (Fast Fourier transform)
to canvas (frequency of voice generator l) that shows alongside the slider
as it moves. just like voice not player of whatsapp

**Comment by guruatdigni** [comment]
Still got this issue, i am using the latest one
